version: '3.4'

services:
  sampleproject:
    image: stsiarzhanau/car-rental:v0.1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
